version: '3.8'

services:
  postgres:
    image: postgres:13.16-bookworm
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: test
